### ISSUE TITLE
Methods - Annotation section.

### ISSUE THREAD

**Issue by sr320** [jldimond/Coral-CpG-ratio-MS#8]
In Annotation section - links will not work. This would need to be written so someone could reproduce. 
Where were tables obtained from? Eventually jupyter notebooks will also need doi and citations like any other reference.

**Comment by jldimond** [comment]
OK. All of these tools and resources are very new to me so I wasn't sure what the proper protocol is for citing/reporting in a manuscript. Can you help me with describing the SQL share tables and citing them? I'm not sure where you originally got the data from or how to cite.

Also not sure at this point how to get doi for notebooks and cite, but I can probably figure it out. Do you think we could get away with just one annotation workflow, and another for the CpG workflow, for all transcriptomes? There were some minor differences between the analyses, mainly in dealing with the different headers in the FASTA files. But otherwise the analyses are pretty much the same.

**Comment by sr320** [comment]
Yes - I can deal with citing tables. 

Can deal with formal citations of nbs at end.
